### ISSUE TITLE
Requirement installation not worked

### ISSUE THREAD

**Issue by robinroby** [jveronvialard/local-agent#1]
Hi,
I was eager to try installing your local agent. But pip installing with default requirement.txt does not work properly

Don't know whether i did somthing wrong, but i try to modify step by step to get first initial installation by executing
pip install -r requirements.txt

Window
1. Pip Version > 3.7 and under 3.11
2. whispercpp==1.0 is not available
ERROR: Ignored the following yanked versions: 0.0.3, 0.0.4, 0.0.9
ERROR: Could not find a version that satisfies the requirement whispercpp==1.0 (from versions: 0.0.6, 0.0.7, 0.0.8, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.15, 0.0.16, 0.0.17)
ERROR: No matching distribution found for whispercpp==1.0
-> change to _whispercpp==0.0.17_
3. 
[log.txt](https://github.com/jveronvialard/local-agent/files/14822499/log.txt)

**Comment by jveronvialard** [comment]
Thank you for trying it out! 
[EDIT] I migrated to [faster-whisper](https://github.com/SYSTRAN/faster-whisper) which is better maintained. Please take a look at the updated README. I tested the install on MacOS and Windows. For Windows you'll need to run "env\Scripts\activate" to activate the environment.
FYI Whisper is only needed for audio-to-text applications (e.g. asking questions about a YouTube video) so you can skip it if you are actually interested in other applications.
Please let me know if this solves your issue.

**Comment by robinroby** [comment]
The installation gets through after adding the build tools 
https://stackoverflow.com/questions/77267346/error-while-installing-python-package-llama-cpp-python.

My Laptop is low on RAM, that's why i can't run it 
Window
(env) C:\PROJECTS\local-agent>python evaluation.py --model_path ./models/Nous-Hermes-2-Yi-34B.Q3_K_M.gguf
Namespace(model_path='./models/Nous-Hermes-2-Yi-34B.Q3_K_M.gguf')
# Tools - Basic
## Get Quote
### Fake Service - Fixed price
  0%|
